import type { AddictionTypeConfig } from "@/types/addiction";

export const TOBACCO_MILESTONES = [
  { time: 0.33, titleKey: "m_heartRateDrops", descKey: "m_heartRateDropsDesc" },
  { time: 8, titleKey: "m_oxygenNormalizes", descKey: "m_oxygenNormalizesDesc" },
  { time: 24, titleKey: "m_heartAttackRiskDrops", descKey: "m_heartAttackRiskDropsDesc" },
  { time: 48, titleKey: "m_nerveEndingsRegrow", descKey: "m_nerveEndingsRegrowDesc" },
  { time: 72, titleKey: "m_breathingImproves", descKey: "m_breathingImprovesDesc" },
  { time: 336, titleKey: "m_circulationRestored", descKey: "m_circulationRestoredDesc" },
  { time: 2160, titleKey: "m_coughingDecreases", descKey: "m_coughingDecreasesDesc" },
  { time: 8760, titleKey: "m_riskHalved", descKey: "m_riskHalvedDesc" },
  { time: 43800, titleKey: "m_lungCancerRiskHalved", descKey: "m_lungCancerRiskHalvedDesc" },
  { time: 87600, titleKey: "m_riskNormalized", descKey: "m_riskNormalizedDesc" },
];

export const ALCOHOL_MILESTONES = [
  { time: 6, titleKey: "m_alcoholSugarStabilizes", descKey: "m_alcoholSugarStabilizesDesc" },
  { time: 24, titleKey: "m_alcoholWithdrawalPeaks", descKey: "m_alcoholWithdrawalPeaksDesc" },
  { time: 72, titleKey: "m_alcoholDetoxComplete", descKey: "m_alcoholDetoxCompleteDesc" },
  { time: 168, titleKey: "m_alcoholSleepImproves", descKey: "m_alcoholSleepImprovesDesc" },
  { time: 336, titleKey: "m_alcoholSkinImproves", descKey: "m_alcoholSkinImprovesDesc" },
  { time: 720, titleKey: "m_alcoholBPNormalizes", descKey: "m_alcoholBPNormalizesDesc" },
  { time: 2160, titleKey: "m_alcoholLiverFat", descKey: "m_alcoholLiverFatDesc" },
  { time: 8760, titleKey: "m_alcoholLiverRecovery", descKey: "m_alcoholLiverRecoveryDesc" },
];

export const CANNABIS_MILESTONES = [
  { time: 1, titleKey: "m_cannabisHighFades", descKey: "m_cannabisHighFadesDesc" },
  { time: 24, titleKey: "m_cannabisWithdrawalStarts", descKey: "m_cannabisWithdrawalStartsDesc" },
  { time: 72, titleKey: "m_cannabisTHCDeclining", descKey: "m_cannabisTHCDecliningDesc" },
  { time: 168, titleKey: "m_cannabisSleepImproves", descKey: "m_cannabisSleepImprovesDesc" },
  { time: 720, titleKey: "m_cannabisLungsClearing", descKey: "m_cannabisLungsClearingDesc" },
  { time: 2160, titleKey: "m_cannabisCognitiveRecovery", descKey: "m_cannabisCognitiveRecoveryDesc" },
];

export const CAFFEINE_MILESTONES = [
  { time: 12, titleKey: "m_caffeineWithdrawalStarts", descKey: "m_caffeineWithdrawalStartsDesc" },
  { time: 24, titleKey: "m_caffeineHeadachePeaks", descKey: "m_caffeineHeadachePeaksDesc" },
  { time: 48, titleKey: "m_caffeineBrainAdapting", descKey: "m_caffeineBrainAdaptingDesc" },
  { time: 168, titleKey: "m_caffeineSleepNormalizes", descKey: "m_caffeineSleepNormalizesDesc" },
  { time: 336, titleKey: "m_caffeineEnergyStabilizes", descKey: "m_caffeineEnergyStabilizesDesc" },
];

export const BEHAVIORAL_MILESTONES = [
  { time: 24, titleKey: "m_behavioralFirstDay", descKey: "m_behavioralFirstDayDesc" },
  { time: 72, titleKey: "m_behavioralCravingsPeak", descKey: "m_behavioralCravingsPeakDesc" },
  { time: 168, titleKey: "m_behavioralOneWeek", descKey: "m_behavioralOneWeekDesc" },
  { time: 720, titleKey: "m_behavioralNewHabits", descKey: "m_behavioralNewHabitsDesc" },
  { time: 2160, titleKey: "m_behavioralThreeMonths", descKey: "m_behavioralThreeMonthsDesc" },
  { time: 8760, titleKey: "m_behavioralOneYear", descKey: "m_behavioralOneYearDesc" },
];

export const ADDICTION_TYPES: AddictionTypeConfig[] = [
  // Tobacco
  {
    id: "cigarette",
    category: "tobacco",
    icon: "cigarette",
    labelKey: "cigarette",
    counterLabelKey: "timeSinceLastCigarette",
    unitLabelKey: "cigarettesAvoided",
    defaultPerDay: 20,
    caloriesPerUnit: 0,
    showPerDay: true,
    showPatchTracker: true,
    showReductionMode: false,
    milestones: TOBACCO_MILESTONES,
    statKeys: ["unitsAvoided", "moneySaved"],
  },
  {
    id: "vape",
    category: "tobacco",
    icon: "vape",
    labelKey: "vape",
    counterLabelKey: "timeSinceLastVape",
    unitLabelKey: "sessionsAvoided",
    defaultPerDay: 10,
    caloriesPerUnit: 0,
    showPerDay: false,
    showPatchTracker: false,
    showReductionMode: false,
    milestones: TOBACCO_MILESTONES,
    statKeys: ["unitsAvoided", "moneySaved"],
  },
  {
    id: "iqos",
    category: "tobacco",
    icon: "iqos",
    labelKey: "iqos",
    counterLabelKey: "timeSinceLastIqos",
    unitLabelKey: "sticksAvoided",
    defaultPerDay: 20,
    caloriesPerUnit: 0,
    showPerDay: true,
    showPatchTracker: true,
    showReductionMode: false,
    milestones: TOBACCO_MILESTONES,
    statKeys: ["unitsAvoided", "moneySaved"],
  },
  {
    id: "snus",
    category: "tobacco",
    icon: "snus",
    labelKey: "snus",
    counterLabelKey: "timeSinceLastSnus",
    unitLabelKey: "pouchesAvoided",
    defaultPerDay: 12,
    caloriesPerUnit: 0,
    showPerDay: true,
    showPatchTracker: true,
    showReductionMode: false,
    milestones: TOBACCO_MILESTONES,
    statKeys: ["unitsAvoided", "moneySaved"],
  },
  {
    id: "nicotine_gum",
    category: "tobacco",
    icon: "nicotine_gum",
    labelKey: "nicotineGum",
    counterLabelKey: "timeSinceLastGum",
    unitLabelKey: "gumsAvoided",
    defaultPerDay: 10,
    caloriesPerUnit: 0,
    showPerDay: true,
    showPatchTracker: false,
    showReductionMode: false,
    milestones: TOBACCO_MILESTONES,
    statKeys: ["unitsAvoided", "moneySaved"],
  },
  {
    id: "nicotine_spray",
    category: "tobacco",
    icon: "nicotine_spray",
    labelKey: "nicotineSpray",
    counterLabelKey: "timeSinceLastSpray",
    unitLabelKey: "spraysAvoided",
    defaultPerDay: 8,
    caloriesPerUnit: 0,
    showPerDay: true,
    showPatchTracker: false,
    showReductionMode: false,
    milestones: TOBACCO_MILESTONES,
    statKeys: ["unitsAvoided", "moneySaved"],
  },
  // Alcohol
  {
    id: "alcohol",
    category: "alcohol",
    icon: "alcohol",
    labelKey: "alcohol",
    counterLabelKey: "timeSinceLastDrink",
    unitLabelKey: "drinksAvoided",
    defaultPerDay: 4,
    caloriesPerUnit: 150,
    showPerDay: true,
    showPatchTracker: false,
    showReductionMode: true,
    milestones: ALCOHOL_MILESTONES,
    statKeys: ["unitsAvoided", "moneySaved", "caloriesSaved"],
  },
  // Substances
  {
    id: "cannabis",
    category: "substance",
    icon: "cannabis",
    labelKey: "cannabis",
    counterLabelKey: "timeSinceLastCannabis",
    unitLabelKey: "sessionsAvoidedCannabis",
    defaultPerDay: 3,
    caloriesPerUnit: 0,
    showPerDay: true,
    showPatchTracker: false,
    showReductionMode: true,
    milestones: CANNABIS_MILESTONES,
    statKeys: ["unitsAvoided", "moneySaved"],
  },
  {
    id: "caffeine",
    category: "substance",
    icon: "caffeine",
    labelKey: "caffeine",
    counterLabelKey: "timeSinceLastCaffeine",
    unitLabelKey: "cupsAvoided",
    defaultPerDay: 4,
    caloriesPerUnit: 5,
    showPerDay: true,
    showPatchTracker: false,
    showReductionMode: true,
    milestones: CAFFEINE_MILESTONES,
    statKeys: ["unitsAvoided", "moneySaved"],
  },
  // Behavioral
  {
    id: "gambling",
    category: "behavioral",
    icon: "gambling",
    labelKey: "gambling",
    counterLabelKey: "timeSinceLastGamble",
    unitLabelKey: "sessionsAvoidedGambling",
    defaultPerDay: 1,
    caloriesPerUnit: 0,
    showPerDay: false,
    showPatchTracker: false,
    showReductionMode: false,
    milestones: BEHAVIORAL_MILESTONES,
    statKeys: ["moneySaved"],
  },
  {
    id: "social_media",
    category: "behavioral",
    icon: "social_media",
    labelKey: "socialMedia",
    counterLabelKey: "timeSinceLastScroll",
    unitLabelKey: "hoursReclaimed",
    defaultPerDay: 4,
    caloriesPerUnit: 0,
    showPerDay: true,
    showPatchTracker: false,
    showReductionMode: true,
    milestones: BEHAVIORAL_MILESTONES,
    statKeys: ["unitsAvoided"],
  },
  {
    id: "gaming",
    category: "behavioral",
    icon: "gaming",
    labelKey: "gaming",
    counterLabelKey: "timeSinceLastGame",
    unitLabelKey: "hoursReclaimedGaming",
    defaultPerDay: 5,
    caloriesPerUnit: 0,
    showPerDay: true,
    showPatchTracker: false,
    showReductionMode: true,
    milestones: BEHAVIORAL_MILESTONES,
    statKeys: ["unitsAvoided"],
  },
  {
    id: "pornography",
    category: "behavioral",
    icon: "pornography",
    labelKey: "pornography",
    counterLabelKey: "timeSinceLastPorn",
    unitLabelKey: "sessionsAvoidedPorn",
    defaultPerDay: 1,
    caloriesPerUnit: 0,
    showPerDay: false,
    showPatchTracker: false,
    showReductionMode: false,
    milestones: BEHAVIORAL_MILESTONES,
    statKeys: ["unitsAvoided"],
  },
  {
    id: "shopping",
    category: "behavioral",
    icon: "shopping",
    labelKey: "shopping",
    counterLabelKey: "timeSinceLastShopping",
    unitLabelKey: "impulsesPrevented",
    defaultPerDay: 1,
    caloriesPerUnit: 0,
    showPerDay: false,
    showPatchTracker: false,
    showReductionMode: false,
    milestones: BEHAVIORAL_MILESTONES,
    statKeys: ["moneySaved"],
  },
  {
    id: "self_harm",
    category: "behavioral",
    icon: "self_harm",
    labelKey: "selfHarm",
    counterLabelKey: "timeSinceLastSelfHarm",
    unitLabelKey: "daysFreeSelfHarm",
    defaultPerDay: 1,
    caloriesPerUnit: 0,
    showPerDay: false,
    showPatchTracker: false,
    showReductionMode: false,
    milestones: BEHAVIORAL_MILESTONES,
    statKeys: ["unitsAvoided"],
  },
];

export function getAddictionConfig(typeId: string): AddictionTypeConfig {
  return ADDICTION_TYPES.find(a => a.id === typeId) || ADDICTION_TYPES[0];
}
